name: Validate build

on: push

# env:
#   APP_ID: '${{ secrets.SYMBL_APPID }}'
#   APP_SECRET: '${{ secrets.SYMBL_APPSECRET }}'
#   ACCESS_TOKEN: null
#   EXPIRED_ACCESS_TOKEN: '${{ secrets.SYMBL_EXPIRED }}'

jobs:
  validate_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install Dependencies
        run: npm install
      
      - name: Run ESLint
        run: npm run lint

      - name: Authenticate with Symbl for Access Token
        id: accessTokenRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.symbl.ai/oauth2/token:generate'
          method: 'POST'
          type: 'application'
          appId: ${{ secrets.SYMBL_APPID }}
          appSecret: ${{ secrets.SYMBL_APPSECRET }}
        
        name: Access Token pushed to env variable
        run: echo ${{ steps.accessTokenRequest.outputs.response.accessToken }} >> env.ACCESS_TOKEN

      - name: Run tests
        run: npm run test
