name: Validate build

on: push

env:
  APP_ID: '${{ secrets.APP_ID }}'
  APP_SECRET: '${{ secrets.APP_SECRET }}'
  EXPIRED_ACCESS_TOKEN: '${{ secrets.EXPIRED_ACCESS_TOKEN }}'

jobs:
  validate_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install Dependencies
        run: npm install
      
      - name: Run ESLint
        run: npm run lint

      - name: Authenticate with Symbl for Access Token
        id: accessTokenRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.symbl.ai/oauth2/token:generate'
          method: 'POST'
          data: '{"type":"application","appId":"${{ secrets.APP_ID }}","appSecret":"${{ secrets.APP_SECRET }}"}'
        
      - name: Access Token pushed to env variable
        run: echo "ACCESS_TOKEN=${{ steps.accessTokenRequest.outputs.response }}" >> $GITHUB_ENV

      - name: Run tests
        run: npm run test
